### ISSUE TITLE
Wrong environment being activate

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-python-environments#34]
- Create two different venvs (e.g. venv1 and venv2)
- Select a folder as a project (e.g. "folder1)
- Select a subfolder of that folder as a project (e.g. "folder1/folder2") 
-  Select one environment for each one of them (e.g. venv1 for folder1 and venv2 for folder2)
- Now open Python a file from folder2, notice that the selected environment updates correctly
- Now open the terminal and click to activate

It seems venv1 is activated instead of venv2:

https://github.com/user-attachments/assets/05b8b84c-6a84-469f-acf0-2863aacb7bd9

**Comment by luabud** [comment]
the LS startup failure notifications on the video are likely because of the environment I deleted as I was testing the other bug I filed

**Comment by karthiknadig** [comment]
@luabud This is actually by design. Terminals are project affine, so when this terminal was activated, it was based on the `cwd` location of the terminal when it was created. For this case you may have to launch it from the project view to get the test environment. We can talk about this in Standup if you feel we need to refine it more.

One thing to note, currently there is a limitation that when terminal cwd is changed from terminal we can't fully detect it. This might improve as shell integration improves, but until that point, we map it to what we can know from Terminal API.

**Comment by luabud** [comment]
I see, that makes sense. Since we have the activation button and we are also able to create a terminal from the project view, I'm closing this as not planned.
